# Generated by Django 3.0.3 on 2020-03-05 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dir', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('file', models.CharField(max_length=40)),
                ('date_publish', models.DateTimeField(verbose_name='date published')),
                ('date_written', models.DateTimeField(verbose_name='date written')),
                ('author', models.CharField(max_length=40)),
                ('publisher', models.CharField(max_length=40)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Section')),
            ],
        ),
    ]
